mydjangoproject/mydjangoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('project.urls')),
    path("users/", include("users.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mydjangoproject/project/urls.py
from django.urls import path
from . import views

app_name = 'project'

urlpatterns = [
    path('', views.main, name = 'main'),
    path('tag/', views.tag,  name = 'tag'),
    path('quote/', views.quote, name='quote'),
    path('author/', views.author, name='author'),
    path('detail/<int:quote_id>', views.quote_info, name='quote_info'),
    path('detail/<str:author_name>', views.about_author, name='about_author'),
]

mydjangoproject/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
]

mydjangoproject/project/models.py
from django.db import models

class Authors(models.Model):
    fullname = models.CharField(max_length=25, null=False, unique=True)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=100, null=False, unique=True)
    description = models.TextField()

    def __str__(self):
        return f"{self.fullname}"


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)
    
    def __str__(self):
        return f"{self.name}"


class Quotes(models.Model):
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Authors, on_delete=models.CASCADE, default=None, null=False)
    quote = models.TextField()

    def __str__(self):
        return f"{self.tags}"

mydjangoproject/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


# Extending User Model Using a One-To-One Link
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='default_avatar.png', upload_to='profile_images')

    def __str__(self):
        return self.user.username

    # resizing images
    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)

        if img.height > 250 or img.width > 250:
            new_img = (250, 250)
            img.thumbnail(new_img)
            img.save(self.avatar.path)
            

mydjangoproject/project/forms.py
from django.forms import ModelForm, CharField, TextInput
from .models import Tag, Quotes, Authors


class TagForm(ModelForm):

    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    
    class Meta:
        model = Tag
        fields = ['name']


class AuthorForm(ModelForm):
    fullname = CharField(min_length=3, max_length=25, required=True, widget=TextInput)

    class Meta:
        model = Authors
        fields = ['fullname', 'born_date', 'born_location', 'description']


class QuoteForm(ModelForm):

    quote = CharField(min_length=5, max_length=50, required=True, widget=TextInput())

    class Meta:
        model = Quotes
        fields = ['quote', 'tags', 'author']

mydjangoproject/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Profile

class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
...

class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']


class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput())

    class Meta:
        model = Profile
        fields = ['avatar']

mydjangoproject/project/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import TagForm, QuoteForm, AuthorForm
from .models import Tag, Quotes, Authors

# Create your views here.
def main(request):
    quotes = Quotes.objects.all()
    return render(request, 'project/index.html', {"quotes": quotes})


def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='project:main')
        else:
            return render(request, 'project/tag.html', {'form': form})

    return render(request, 'project/tag.html', {'form': TagForm()})


def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='project:main')
        else:
            return render(request, 'project/author.html', {'form': form})

    return render(request, 'project/author.html', {'form': AuthorForm()})


def quote(request):
    tags = Tag.objects.all()

    if request.method == "POST":
        form = QuoteForm(request.POST)

        if form.is_valid():
            quote = form.save()
            author_name = form.cleaned_data["author"]
            author = get_object_or_404(Authors, fullname=author_name)
            quote.author = author
            quote.save()
            chosen_tags = form.cleaned_data["tags"]
            quote.tags.set(chosen_tags)
            return redirect(to="project:main")
        
        else:
            return render(request, "project/quote.html", {"tags": tags, "form": form})
        
    return render(request, "project/quote.html", {"tags": tags, "form": QuoteForm()})


def quote_info(request, quote_id):
    quote = get_object_or_404(Quotes, pk=quote_id)
    return render (request, 'project/quote_detail.html', {'quote': quote})


def about_author(request, author_name):
    author = get_object_or_404(Authors, fullname=author_name)
    return render(request, "project/author_detail.html", {"author": author})

mydjangoproject/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Profile

from .forms import RegisterForm, LoginForm, ProfileForm

def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='project:main')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='project:main')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})

def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to='project:main')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='project:main')

    return render(request, 'users/login.html', context={"form": LoginForm()})

@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='project:main')

from django.core.exceptions import ObjectDoesNotExist

@login_required
def profile(request):
    try:
        profile_instance = request.user.profile
    except ObjectDoesNotExist:
        profile_instance = None

    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, request.FILES, instance=profile_instance)
        if profile_form.is_valid():
            profile = profile_form.save(commit=False)
            profile.user = request.user
            profile.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='users:profile')

    profile_form = ProfileForm(instance=profile_instance)
    return render(request, 'users/profile.html', {'profile_form': profile_form})

mydjangoproject/project/templates/project/author.html
{% extends "project/base.html" %} {% block content %}

<form method="POST" action="{% url 'project:author' %}">
  {% csrf_token %}
  <div style="padding: 10px">
    <label> Author name: {{ form.fullname }} </label>
    <span>{{ form.errors.name }}</span>
  </div>
  <div style="padding: 10px">
    <label> Born date: {{ form.born_date }} </label>
    <laber> Born location: {{form.born_location}} </laber>
    <span>{{ form.errors.name }}</span>
  </div>
  <div style="padding: 10px">
    <label> Author description: {{ form.description }} </label>
    <span>{{ form.errors.description }}</span>
  </div>
  <div class="grid">
    <button type="submit">Add author</button>
    <button type="reset" class="secondary">Reset</button>
  </div>
</form>
{% endblock %}

mydjangoproject/project/templates/project/author_detail.html
{% extends "project/base.html" %} {% block content %}

<h1>{{author.fullname}}</h1>
<p>Born: <b>{{author.born_date}}</b> <b>{{author.born_location}}</b></p>
<p>Description: <bd>{{author.description}}</bd></p>
{% endblock %}

mydjangoproject/project/templates/project/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Quote information</title>
    <link
      rel="stylesheet"
      href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"
    />
    {% load static %}
    <link rel="stylesheet" href="{% static 'project/style.css' %}" />
  </head>
  <body>
    <main class="container">
      <nav
        style="
          margin-bottom: 20px;
          border-bottom: 2px solid;
          padding-left: 30px;
        "
      >
        <ul>
          <li><a href="/" role="button"> Go back to the main page </a></li>
        </ul>
      </nav>
      {% block content %} {% endblock %}
    </main>
  </body>
</html>

mydjangoproject/project/templates/project/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Organizer</title>
    <link
      rel="stylesheet"
      href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"
    />
  </head>
  <body>
    <main class="container">
      <nav
        style="
          margin-bottom: 20px;
          border-bottom: 2px solid;
          padding-left: 30px;
        "
      >
        {% if user.is_authenticated %}
        <ul>
          <li>
            <a href="{% url 'project:quote' %}" role="button">Add quote:</a>
          </li>
          <li>
            <a href="{% url 'project:author' %}" role="button">Add Author:</a>
          </li>
          <li><a href="{% url 'project:tag' %}" role="button">Add tag:</a></li>
        </ul>
        <ul>
          <li>Welcome <b>{{ user.username }}!</b></li>
          <li><a href="{% url 'users:profile' %}" role="button">Profile</a></li>
          <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
        </ul>
        {% else %}
        <ul>
          <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
          <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
        </ul>
        {% endif %}
      </nav>
      {% for quote in quotes %}
      <ul>
        <li>
          <a
            href="{% url 'project:quote_info' quote.id %}"
            role="button"
            class="outline"
          >
            {{ quote.quote }}
          </a>
        </li>
      </ul>
      {% endfor %}
    </main>
  </body>
</html>

mydjangoproject/project/templates/project/quote.html
{% extends "project/base.html" %} {% block content %}

<form method="POST" action="{% url 'project:quote' %}">
  {% csrf_token %}
  <div style="padding: 10px">
    <label> Authors name: {{ form.author }} </label>
    <span>{{ form.errors.author }}</span>
  </div>

  <div style="padding: 10px">
    <label> Quotes text: {{ form.quote }} </label>
    <span>{{ form.errors.quote }}</span>
  </div>

  <div style="padding: 10px">
    <label> Tags: {{ form.tags }} </label>
    <span>{{ form.errors.tags }}</span>
  </div>

  <div class="grid">
    <button type="submit">Add quote</button>
    <button type="reset" class="secondary">Reset</button>
  </div>
</form>
{% endblock %}

mydjangoproject/project/templates/project/quote_detail.html
{% extends "project/base.html" %} {% load extract %} {% block content %}

<b>{{ quote.quote }}</b>
<p>
  <b>by: <kbd>{{ quote.author }}</kbd></b>
</p>
<a href="{% url 'project:about_author' author_name=quote.author.fullname %}"
  >(about)</a
>

<p>Tags: <b>{{ quote.tags|tags }}</b></p>

{% endblock %}

mydjangoproject/project/templates/project/tag.html
{% extends "project/base.html" %} {% block content %}

<form method="POST" action="{% url 'project:tag' %}">
  {% csrf_token %}
  <div style="padding: 10px">
    <label>Enter the tag name: {{form.name}} </label>
    <span>{{ form.errors.name }}</span>
  </div>
  <div class="grid">
    <button type="submit">Add tag</button>
    <button type="reset" class="secondary">Reset</button>
  </div>
</form>

{% endblock %}

mydjangoproject/users/templates/users/login.html
{% extends "project/base.html" %} {% block content %} {% if messages %}
<div>
  {% for message in messages %}
  <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>
    {{ message }}
  </div>
  {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
  {% csrf_token %}
  <div>
    <label> Username: {{ form.username }} </label>
  </div>

  <div>
    <label>Password: {{ form.password }} </label>
  </div>

  <div class="grid">
    <button type="submit">Login</button>
    <button type="reset" class="secondary">Reset</button>
  </div>
</form>

{% endblock %}

mydjangoproject/users/templates/users/profile.html
{% extends "project/base.html" %} {% block content %}

<div>
  <h1>Profile page: {{user.username}}</h1>
  <img src="{{ user.profile.avatar.url }}" alt="avatar of user" />
</div>

{% if messages %}
<div>
  {% for message in messages %}
  <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>
    {{ message }}
  </div>
  {% endfor %}
</div>
{% endif %}

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-row">
    <div class="col-md-5">
      <div class="form-group">
        <label class="small mb-1">Change Avatar:</label>
        {{ profile_form.avatar }}
        <span>{{ profile_form.errors.avatar }}</span>
      </div>
    </div>
  </div>
  <div class="grid">
    <button type="submit">Save Changes</button>
    <button type="reset" class="secondary">Reset</button>
  </div>
</form>

{% endblock content %}

mydjangoproject/users/templates/users/signup.html
{% extends "project/base.html" %} {% block content %}

<div>
  <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
  {% csrf_token %}
  <div>
    <label> Username: {{ form.username }} </label>
    <span>{{ form.errors.username }}</span>
  </div>
  <br />
  <div>
    <label> Password: {{ form.password1 }} </label>
    <span>{{ form.errors.password1 }}</span>
  </div>
  <div>
    <label> Password confirmation: {{ form.password2 }} </label>
    <span>{{ form.errors.password2 }}</span>
  </div>
  <div class="grid">
    <button type="submit">Register</button>
    <button type="reset" class="secondary">Reset</button>
  </div>
</form>

{% endblock %}